server:
  port: 83
#  servlet:
#    context-path: /nqs-web
spring:
  application:
    name: service-web
  cloud:
    nacos:
      discovery:
        server-addr: 121.37.141.206:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  resources:
    static-locations: classpath:/statics/ ,file:${file.path}}
  profiles:
    active: dev
  freemarker:
    suffix: .html
    request-context-attribute: request
  mvc:
    static-path-pattern: /**
management:
  endpoints:
    web:
      exposure:
        include: '*'

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://service-pdc
feign:
  sentinel:
    enabled: true # 激活Sentinel对Feign的支持
nqs:
  cluster: false  #集群配置  true集群环境   false单机环境，还需打开pom.xml里的spring-session-data-redis注释
  globalSessionTimeout: 3600   #单机环境，session过期时间为60分钟
  redis:
    open: false  #是否开启redis缓存  true开启   false关闭

file:
  #  path: C:/Users/Administrator/Desktop/statics/
  path: /home/work/jiahe/statics/

